// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "about" section.

import React from 'react';
import AboutMediaOverlay from '@/components/sections/about/AboutMediaOverlay';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function AboutSection(): React.JSX.Element {
  return (
    <div id="about" data-section="about">
        <SectionErrorBoundary name="about">
              <AboutMediaOverlay
          tag="Our Story"
          title="Crafted with Passion"
          description="Our journey began with a simple belief that food should be an experience, bringing together fresh farm ingredients and expert culinary skills to delight your senses."
          primaryButton={{
            text: "Read Our Story",
            href: "#",
          }}
          imageSrc="http://img.b2bpic.net/free-photo/various-healthy-vegetables-colander-marble-tabletop_23-2147956577.jpg"
        />
        </SectionErrorBoundary>
      </div>
  );
}
