// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "features" section.

import React from 'react';
import FeaturesMediaCarousel from '@/components/sections/features/FeaturesMediaCarousel';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function FeaturesSection(): React.JSX.Element {
  return (
    <div id="features" data-section="features">
        <SectionErrorBoundary name="features">
              <FeaturesMediaCarousel
          tag="What We Offer"
          title="Signature Experiences"
          description="Discover our culinary highlights."
          items={[
            {
              title: "Fresh Pasta",
              description: "Authentic handmade recipes.",
              buttonIcon: "Utensils",
              imageSrc: "http://img.b2bpic.net/free-photo/top-view-bread-ingredients_23-2149395314.jpg",
            },
            {
              title: "Farm to Table",
              description: "Sourced locally every morning.",
              buttonIcon: "Sprout",
              imageSrc: "http://img.b2bpic.net/free-photo/tomatoes-stall-market-sanarysurmer_268835-3781.jpg",
            },
            {
              title: "Global Flavors",
              description: "International culinary techniques.",
              buttonIcon: "Globe",
              imageSrc: "http://img.b2bpic.net/free-photo/top-view-fresh-meat-slice-with-toamtoes-light-gray-background-animal-cow-chicken-meat-butcher-food-kitchen-color_179666-45992.jpg",
            },
          ]}
        />
        </SectionErrorBoundary>
      </div>
  );
}
