// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "hero" section.

import React from 'react';
import HeroOverlay from '@/components/sections/hero/HeroOverlay';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function HeroSection(): React.JSX.Element {
  return (
    <div id="hero" data-section="hero">
        <SectionErrorBoundary name="hero">
              <HeroOverlay
          tag="Culinary Perfection"
          title="Where Taste Meets Art"
          description="Experience hand-crafted meals prepared with the freshest ingredients and passion."
          primaryButton={{
            text: "Explore Menu",
            href: "#products",
          }}
          secondaryButton={{
            text: "Contact Us",
            href: "#contact",
          }}
          imageSrc="http://img.b2bpic.net/free-photo/high-angle-arrangement-with-vegetables_23-2148494042.jpg"
        />
        </SectionErrorBoundary>
      </div>
  );
}
