// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "metrics" section.

import React from 'react';
import MetricsFeatureCards from '@/components/sections/metrics/MetricsFeatureCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function MetricsSection(): React.JSX.Element {
  return (
    <div id="metrics" data-section="metrics">
        <SectionErrorBoundary name="metrics">
              <MetricsFeatureCards
          tag="Our Stats"
          title="Culinary Excellence"
          description="Quality defined by numbers."
          metrics={[
            {
              value: "12+",
              title: "Years Experience",
              features: [
                "Expertise",
                "Tradition",
              ],
            },
            {
              value: "5k+",
              title: "Happy Diners",
              features: [
                "Satisfied",
                "Loyal",
              ],
            },
            {
              value: "100%",
              title: "Fresh Ingredients",
              features: [
                "Quality",
                "Local",
              ],
            },
          ]}
        />
        </SectionErrorBoundary>
      </div>
  );
}
