// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "pricing" section.

import React from 'react';
import PricingHighlightedCards from '@/components/sections/pricing/PricingHighlightedCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function PricingSection(): React.JSX.Element {
  return (
    <div id="pricing" data-section="pricing">
        <SectionErrorBoundary name="pricing">
              <PricingHighlightedCards
          tag="Pricing Plans"
          title="Dinner Packages"
          description="Flexible options for every dining need."
          plans={[
            {
              tag: "Quick Meal",
              price: "$29",
              description: "Standard 2-course meal.",
              features: [
                "Starter",
                "Main Dish",
              ],
              primaryButton: {
                text: "Select",
                href: "#",
              },
            },
            {
              tag: "Full Experience",
              price: "$55",
              description: "Comprehensive tasting menu.",
              features: [
                "3-Course Meal",
                "Appetizer",
                "Wine Pairing",
                "Dessert",
              ],
              highlight: "Best Value",
              primaryButton: {
                text: "Select",
                href: "#",
              },
            },
            {
              tag: "Chef Private",
              price: "$120",
              description: "Private exclusive culinary experience.",
              features: [
                "Custom Menu",
                "Chef Interaction",
                "Premium Wine",
              ],
              primaryButton: {
                text: "Book",
                href: "#",
              },
            },
          ]}
        />
        </SectionErrorBoundary>
      </div>
  );
}
