// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "products" section.

import React from 'react';
import FeaturesRevealCardsBento from '@/components/sections/features/FeaturesRevealCardsBento';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function ProductsSection(): React.JSX.Element {
  return (
    <div id="products" data-section="products">
        <SectionErrorBoundary name="products">
              <FeaturesRevealCardsBento
          tag="Our Menu"
          title="Chef Specials"
          description="A curated selection of our finest dishes."
          items={[
            {
              title: "Truflle Pasta",
              description: "Rich, earthy flavors.",
              href: "#",
              imageSrc: "http://img.b2bpic.net/free-photo/salad-with-red-caviar-salmon-avocado_140725-6797.jpg",
            },
            {
              title: "Grilled Salmon",
              description: "Fresh wild-caught salmon.",
              href: "#",
              imageSrc: "http://img.b2bpic.net/free-photo/top-view-fried-eggplant-with-tomato-chopped-green-onions-rag-round-white-plate_176474-3356.jpg",
            },
            {
              title: "Ribeye Steak",
              description: "Perfectly seared to taste.",
              href: "#",
              imageSrc: "http://img.b2bpic.net/free-photo/fried-spicy-razor-clams_1203-9555.jpg",
            },
            {
              title: "Garden Salad",
              description: "Fresh seasonal greens.",
              href: "#",
              imageSrc: "http://img.b2bpic.net/free-photo/beautiful-arrangement-spanish-food_23-2149157429.jpg",
            },
            {
              title: "Artisan Bread",
              description: "Freshly baked daily.",
              href: "#",
              imageSrc: "http://img.b2bpic.net/free-photo/assortment-thanksgiving-day-delicious-dinner_23-2149100164.jpg",
            },
            {
              title: "Dessert Trio",
              description: "Sweet finale of flavors.",
              href: "#",
              imageSrc: "http://img.b2bpic.net/free-photo/delicious-healthy-food-arrangement_23-2149043084.jpg",
            },
            {
              title: "Organic Wine",
              description: "Selected premium vintages.",
              href: "#",
              imageSrc: "http://img.b2bpic.net/free-photo/top-view-delicious-eggplant-rolls-with-baked-potatoes-inside-plate-dark-background-dish-meal-dinner-food-potato-vegetable_140725-116119.jpg",
            },
          ]}
        />
        </SectionErrorBoundary>
      </div>
  );
}
