// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "testimonials" section.

import React from 'react';
import TestimonialColumnMarqueeCards from '@/components/sections/testimonial/TestimonialColumnMarqueeCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function TestimonialsSection(): React.JSX.Element {
  return (
    <div id="testimonials" data-section="testimonials">
        <SectionErrorBoundary name="testimonials">
              <TestimonialColumnMarqueeCards
          tag="Reviews"
          title="What Diners Say"
          description="Hear about our unique culinary journey."
          testimonials={[
            {
              name: "Alice Smith",
              role: "Food Blogger",
              quote: "The best dining experience ever!",
              imageSrc: "http://img.b2bpic.net/free-photo/happy-asian-woman-shows-thumbs-up-approves-likes-smth-good-stands-near-cafe-entrance-give-her_1258-199002.jpg",
            },
            {
              name: "John Doe",
              role: "Gourmet Critic",
              quote: "Absolutely exquisite flavors.",
              imageSrc: "http://img.b2bpic.net/free-photo/successful-young-man-stylish-hat-relaxing-alone-cozy-cafeteria-lunch-break-looking-with-happy-expression_273609-1935.jpg",
            },
            {
              name: "Maria Garcia",
              role: "Chef",
              quote: "True dedication to the craft.",
              imageSrc: "http://img.b2bpic.net/free-photo/male-local-traveler-with-camera_23-2149016703.jpg",
            },
            {
              name: "David Brown",
              role: "Traveler",
              quote: "Exceeded all my expectations.",
              imageSrc: "http://img.b2bpic.net/free-photo/portrait-smiling-brunette-woman-drinks-morning-coffee-cafe_613910-12134.jpg",
            },
            {
              name: "Sophia Lee",
              role: "Local",
              quote: "My favorite spot for celebrations.",
              imageSrc: "https://storage.googleapis.com/webild/default/no-image.jpg?id=z4z6v0",
            },
          ]}
        />
        </SectionErrorBoundary>
      </div>
  );
}
